runtime: python39
instance_class: F1

automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: 30s

env_variables:
  FLASK_ENV: production

handlers:
- url: /.*
  script: auto
